### ISSUE TITLE
about ReadMoreTextView

### ISSUE THREAD

**Issue by pudao2010** [bravoborja/ReadMoreTextView#19]
I am sorry my English, I am chinese
If We customize ReadMoreTextView with app:trimExpandedText="收起" in xml file, It cant response?
When I try ReadMoreTextView .setTrimCollapsedText in java code, It can response

**Comment by borjabravo10** [comment]
Hi @pudao2010 you're mixing two differents terms.
"setTrimCollapsedText" allow you show a text collapsed. 
However, trimExpandedText in the xml show a text expanded. If the trimLength is higher than text length, you only see it the text Expanded.

What is your problem?
